version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: 'npm'
    directory: '/ui'
    schedule:
      interval: 'weekly'

  - package-ecosystem: "docker"
    directory: "/images"
    schedule:
      interval: "weekly"
