openapi: 3.0.3
info:
  title: Tekton Hub
  description: HTTP services for managing Tekton Hub
  version: "0.1"
servers:
- url: api.hub.tekton.dev
paths:
  /categories:
    get:
      tags:
      - category
      summary: list category
      description: List all categories along with their tags sorted by name
      operationId: category#list
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
                example:
                - id: 1
                  name: Image Builder
                  tags:
                  - id: 1
                    name: image-build
                  - id: 2
                    name: kaniko
                - id: 1
                  name: Image Builder
                  tags:
                  - id: 1
                    name: image-build
                  - id: 2
                    name: kaniko
                - id: 1
                  name: Image Builder
                  tags:
                  - id: 1
                    name: image-build
                  - id: 2
                    name: kaniko
                - id: 1
                  name: Image Builder
                  tags:
                  - id: 1
                    name: image-build
                  - id: 2
                    name: kaniko
              example:
              - id: 1
                name: Image Builder
                tags:
                - id: 1
                  name: image-build
                - id: 2
                  name: kaniko
              - id: 1
                name: Image Builder
                tags:
                - id: 1
                  name: image-build
                - id: 2
                  name: kaniko
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
  /query:
    get:
      tags:
      - resource
      summary: Query resource
      description: Find resources by a combination of name, type
      operationId: resource#Query
      parameters:
      - name: name
        in: query
        description: Name of resource
        allowEmptyValue: true
        schema:
          type: string
          description: Name of resource
          default: ""
          example: Omnis quas deserunt nostrum assumenda.
        example: Occaecati voluptas assumenda.
      - name: type
        in: query
        description: Type of resource
        allowEmptyValue: true
        schema:
          type: string
          description: Type of resource
          default: ""
          example: ""
          enum:
          - task
          - pipeline
          - ""
        example: pipeline
      - name: limit
        in: query
        description: Maximum number of resources to be returned
        allowEmptyValue: true
        schema:
          type: integer
          description: Maximum number of resources to be returned
          default: 100
          example: 11724777226257936196
        example: 2829482926296309606
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceCollection'
              example:
              - catalog:
                  id: 1
                  type: community
                id: 1
                latestVersion:
                  description: Buildah task builds source into a container image and then pushes it to a container registry.
                  displayName: Buildah
                  id: 1
                  minPipelinesVersion: 0.12.1
                  rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                  updatedAt: 2020-01-01 12:00:00 +0000 UTC
                  version: "0.1"
                  webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
                name: buildah
                rating: 4.3
                tags:
                - id: 1
                  name: image-build
                type: task
              - catalog:
                  id: 1
                  type: community
                id: 1
                latestVersion:
                  description: Buildah task builds source into a container image and then pushes it to a container registry.
                  displayName: Buildah
                  id: 1
                  minPipelinesVersion: 0.12.1
                  rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                  updatedAt: 2020-01-01 12:00:00 +0000 UTC
                  version: "0.1"
                  webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
                name: buildah
                rating: 4.3
                tags:
                - id: 1
                  name: image-build
                type: task
              - catalog:
                  id: 1
                  type: community
                id: 1
                latestVersion:
                  description: Buildah task builds source into a container image and then pushes it to a container registry.
                  displayName: Buildah
                  id: 1
                  minPipelinesVersion: 0.12.1
                  rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                  updatedAt: 2020-01-01 12:00:00 +0000 UTC
                  version: "0.1"
                  webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
                name: buildah
                rating: 4.3
                tags:
                - id: 1
                  name: image-build
                type: task
        "404":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
  /resources:
    get:
      tags:
      - resource
      summary: List resource
      description: List all resources sorted by rating and name
      operationId: resource#List
      parameters:
      - name: limit
        in: query
        description: Maximum number of resources to be returned
        allowEmptyValue: true
        schema:
          type: integer
          description: Maximum number of resources to be returned
          default: 100
          example: 379431535305924829
        example: 16478532048257346201
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceCollection'
              example:
              - catalog:
                  id: 1
                  type: community
                id: 1
                latestVersion:
                  description: Buildah task builds source into a container image and then pushes it to a container registry.
                  displayName: Buildah
                  id: 1
                  minPipelinesVersion: 0.12.1
                  rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                  updatedAt: 2020-01-01 12:00:00 +0000 UTC
                  version: "0.1"
                  webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
                name: buildah
                rating: 4.3
                tags:
                - id: 1
                  name: image-build
                type: task
              - catalog:
                  id: 1
                  type: community
                id: 1
                latestVersion:
                  description: Buildah task builds source into a container image and then pushes it to a container registry.
                  displayName: Buildah
                  id: 1
                  minPipelinesVersion: 0.12.1
                  rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                  updatedAt: 2020-01-01 12:00:00 +0000 UTC
                  version: "0.1"
                  webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
                name: buildah
                rating: 4.3
                tags:
                - id: 1
                  name: image-build
                type: task
              - catalog:
                  id: 1
                  type: community
                id: 1
                latestVersion:
                  description: Buildah task builds source into a container image and then pushes it to a container registry.
                  displayName: Buildah
                  id: 1
                  minPipelinesVersion: 0.12.1
                  rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                  updatedAt: 2020-01-01 12:00:00 +0000 UTC
                  version: "0.1"
                  webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
                name: buildah
                rating: 4.3
                tags:
                - id: 1
                  name: image-build
                type: task
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
  /swagger/swagger.json:
    get:
      tags:
      - swagger
      summary: Download gen/http/openapi.json
      description: JSON document containing the API swagger definition
      operationId: swagger#/swagger/swagger.json
      responses:
        "200":
          description: File downloaded
components:
  schemas:
    Catalog:
      type: object
      properties:
        id:
          type: integer
          description: ID is the unique id of the catalog
          example: 1
        type:
          type: string
          description: Type of catalog
          example: community
          enum:
          - official
          - community
      example:
        id: 1
        type: community
      required:
      - id
      - type
    Category:
      type: object
      properties:
        id:
          type: integer
          description: ID is the unique id of the category
          example: 1
        name:
          type: string
          description: Name of category
          example: Image Builder
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
          description: List of tags associated with the category
          example:
          - id: 1
            name: image-build
          - id: 2
            name: kaniko
      example:
        id: 1
        name: Image Builder
        tags:
        - id: 1
          name: image-build
        - id: 2
          name: kaniko
      required:
      - id
      - name
      - tags
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: true
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: false
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: true
      description: Internal Server Error
      example:
        fault: false
        id: 123abc
        message: parameter 'p' must be an integer
        name: bad_request
        temporary: false
        timeout: false
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
    HubResource:
      type: object
      properties:
        catalog:
          $ref: '#/components/schemas/Catalog'
        id:
          type: integer
          description: ID is the unique id of the resource
          example: 1
        latestVersion:
          $ref: '#/components/schemas/Version'
        name:
          type: string
          description: Name of resource
          example: buildah
        rating:
          type: number
          description: Rating of resource
          example: 4.3
          format: double
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
          description: Tags related to resource
          example:
          - id: 1
            name: image-build
        type:
          type: string
          description: Type of resource
          example: task
      description: The resource type describes resource information.
      example:
        catalog:
          id: 1
          type: community
        id: 1
        latestVersion:
          description: Buildah task builds source into a container image and then pushes it to a container registry.
          displayName: Buildah
          id: 1
          minPipelinesVersion: 0.12.1
          rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
          updatedAt: 2020-01-01 12:00:00 +0000 UTC
          version: "0.1"
          webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
        name: buildah
        rating: 4.3
        tags:
        - id: 1
          name: image-build
        type: task
      required:
      - id
      - name
      - catalog
      - type
      - latestVersion
      - tags
      - rating
    ResourceCollection:
      type: array
      items:
        $ref: '#/components/schemas/HubResource'
      example:
      - catalog:
          id: 1
          type: community
        id: 1
        latestVersion:
          description: Buildah task builds source into a container image and then pushes it to a container registry.
          displayName: Buildah
          id: 1
          minPipelinesVersion: 0.12.1
          rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
          updatedAt: 2020-01-01 12:00:00 +0000 UTC
          version: "0.1"
          webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
        name: buildah
        rating: 4.3
        tags:
        - id: 1
          name: image-build
        type: task
      - catalog:
          id: 1
          type: community
        id: 1
        latestVersion:
          description: Buildah task builds source into a container image and then pushes it to a container registry.
          displayName: Buildah
          id: 1
          minPipelinesVersion: 0.12.1
          rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
          updatedAt: 2020-01-01 12:00:00 +0000 UTC
          version: "0.1"
          webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
        name: buildah
        rating: 4.3
        tags:
        - id: 1
          name: image-build
        type: task
    Tag:
      type: object
      properties:
        id:
          type: integer
          description: ID is the unique id of tag
          example: 1
        name:
          type: string
          description: Name of tag
          example: image-build
      example:
        id: 1
        name: image-build
      required:
      - id
      - name
    Version:
      type: object
      properties:
        description:
          type: string
          description: Description of version
          example: Buildah task builds source into a container image and then pushes it to a container registry.
        displayName:
          type: string
          description: Display name of version
          example: Buildah
        id:
          type: integer
          description: ID is the unique id of resource's version
          example: 1
        minPipelinesVersion:
          type: string
          description: Minimum pipelines version the resource's version is compatible with
          example: 0.12.1
        rawURL:
          type: string
          description: Raw URL of resource's yaml file of the version
          example: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
          format: uri
        updatedAt:
          type: string
          description: Timestamp when version was last updated
          example: 2020-01-01 12:00:00 +0000 UTC
          format: date-time
        version:
          type: string
          description: Version of resource
          example: "0.1"
        webURL:
          type: string
          description: Web URL of resource's yaml file of the version
          example: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
          format: uri
      example:
        description: Buildah task builds source into a container image and then pushes it to a container registry.
        displayName: Buildah
        id: 1
        minPipelinesVersion: 0.12.1
        rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
        updatedAt: 2020-01-01 12:00:00 +0000 UTC
        version: "0.1"
        webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
      required:
      - id
      - version
      - description
      - displayName
      - minPipelinesVersion
      - rawURL
      - webURL
      - updatedAt
