apiVersion: v1
kind: Secret
metadata:
  name: api
type: Opaque
stringData:
  GH_CLIENT_ID: ''
  GH_CLIENT_SECRET: ''
  GHE_URL: ''
  GL_CLIENT_ID: ''
  GL_CLIENT_SECRET: ''
  GLE_URL: ''
  BB_CLIENT_ID: ''
  BB_CLIENT_SECRET: ''
  JWT_SIGNING_KEY: ''
  ACCESS_JWT_EXPIRES_IN: ''
  REFRESH_JWT_EXPIRES_IN: ''
  AUTH_BASE_URL: ''
