apiVersion: v1
kind: Secret
metadata:
  name: api
type: Opaque
stringData:
  GH_CLIENT_ID: ''
  GH_CLIENT_SECRET: ''
  JWT_SIGNING_KEY: ''
  ACCESS_JWT_EXPIRES_IN: ''
  REFRESH_JWT_EXPIRES_IN: ''
  GHE_URL: ''
