apiVersion: v1
kind: Secret
metadata:
  name: db
  namespace: tekton-hub
  labels:
    app: db
type: Opaque
stringData:
  POSTGRESQL_DATABASE: hub
  POSTGRESQL_USER: postgres
  POSTGRESQL_PASSWORD: postgres
  POSTGRESQL_PORT: "5432"
