name: golangci-lint
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:  # yamllint disable-line rule:empty-values
    branches:
      - main 

permissions:
  contents: read
  checks: write  # Used to annotate code in the PR

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: "1.23.x"

    - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: |
          ~/.cache/go-build
          ~/.cache/pip
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Check out code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - uses: alexellis/setup-arkade@b1816384b2260cfd2c023c6798d26075786cfc7f # v3
    - uses: alexellis/arkade-get@9718b1694fa1db91045e0b5ba199732cb18b4387
      with:
        golangci-lint: v1.64.8

    - name: Lint API code
      run: |
        make api-lint

